version: '3.8'

networks:
  postgres:
    driver: bridge

services:
  postgres_db:
    container_name: postgres_db_1
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes: 
      - postgres:/data/postgres
    ports: 
      - "5432:5432"
    networks: 
      - postgres
    restart: always
  
  pgadmin:  
    container_name: postgres_pgadmin_1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5433:80"
    networks:
      - postgres
    restart: always

volumes:
  postgres:
  pgadmin: